const data = [
  "a fi dus cu funia în larg expr. 1. a-și mărturisi rapid vina în anchetă. 2. a se intimida în fața anchetatorilor din cauza lipsei de experiență.     ",
  "apa, ape s.f. (expr. Vine apa!) poliția! ",
  "anti  prefix  antinevralgic. ",
  "bulan, bulane s.n. 1. bastonul supraveghetorului din locul de deținere și din escortă. 2. bărbat fără experiență în relațiile cu femeile. 3. noroc. 4. dos, fund. 5. picior.  ",
  "grandate s.f.pl.  cărți de joc măsluite prin diverse semne aplicate prin scriere sau împungere. ",
  "antreu, antreuri s.n. buzunar. ",
  "mortăciune, mortăciuni s.f. 1. carne de foarte proastă calitatate  pregătită în mâncare. 2. cadavru. 3. crimă. 4. v. mălai mare.  5. deținut bolnav cronic, cu sănătatea șubredă. 6. mandat de executare a pedepsei. ",
  "a fi băgat la salată expr. a fi închis la secția restrictivă. ",
  "a fi față expr. a fi nesincer și răuvoitor. ",
  "a fi gros la pungă expr. a fi foarte bogat. ",
  "figurant, figuranți s.m.  persoană care vrea să pară importantă, dar nu este.",
  "fieroaică expr. argotică bară de metal de dimensiuni mici, ascunsă la pat și folosită în caz de scandal în cameră, iar uneori pentru atac asupra unor deținuți sau cadre. ",
  "fieroasă, fieroase s.f. conservă. ",
  "fiertură, fierturi s.f.  act sexual. ",
  "fomist, fomiști s.m. 1. nesătul. 2. vagabond care își caută hrana prin lăzile și tomberoanele de gunoaie. ",
  "forțos, forțoși adj. puternic.",
  "foșnitoare, foșnitori s.f. bancnotă nou-nouță, proaspăt pusă în circulație. ",
  "fraier, fraieri s.m. 1. membru al completului de judecată. 2. persoană care nu știe să se descurce, să profite într-o anumită împrejurare. 3. victima unui hoț sau escroc. 4. polițist. ",
  "fraier cu cioc expr. persoană de o prostie rară, prost de-a binelea. ",
  "fraieri,  fraieresc vb. v. a face pontul.",
  "fratele meu expr. prieten bun, colaborator, complice. ",
  "târfoman, târfomani s.m. afemeiat. ",
  "târlan, târlani s.m. fraier. ",
  "târnăcop, târnăcoape s.n. nas mare. ",
  "târșală, târșeli s.f. rușine. ",
  "târșă, târșe s.n. deținut rușinos.",
  "târtan, târtani s.m.  v. târlan. ",
  "târtiță,  târtițe s.f. fund, șezut. ",
  "T. B. C. expr. tutun, băutură, cafea. ",
  "telefon, telefoane s.n. lovitură cu palma peste ureche. ",
  "teleguță, teleguțe s.f. pachet cu obiecte coborât cu o sfoară  la geamul unei camere de deținere de la un etaj inferior. ",
  "teleică, teleici s.f. femeie de moravuri ușoare. ",
  "trompă, trompe s.f. nas mare. ",
  "trompetist trompetiști s. m. v. taragotist. ",
  "tron, tronuri s.n. closet. ",
  "tronson, tronsoane s.n. intervalul dintre paturi în camera de deținere. ",
  "troponei s.invar. încălțăminte. ",
  "troscău  s.invar v. trascău.",
  "trosneală  s.f.invar. v. trascău. ",
  "Vasilică  s.propr. v. vardist.  ",
  "vast, vasturi s.n. mâna. ",
  "vastangiu, vastangii s.m. hoț de buzunare. ",
  "vămui, vămuiesc vb. a fura doar o parte din bani sau bunuri. ",
  "a vărsa gușa  expr.1.  spovedanie la preotul pușcăriei.  2.  a-l denunța cadrelor pe un coleg de detenție. 3. a recunoaște fapta comisă. ",
  "a-și vărsa oala expr. v. a vărsa gușa(2). ",
  "vărsător, vărsători s.m. v. a vărsa gușa(2). ",
  "vărsătură, vărsături s.f. posibilă victimă care are puțini bani la ea. ",
  "văruială, văruieli s.f. beție. ",
  "văruit, văruiți adj. beat. ",
  "zurliu, zurlii adj.pl. bolnav psihic. ",
  "zuză adj. v. zurliu.",
  "zvonac, zvonaci s.m. purtător de zvonuri, de informații false în pușcărie. ",
  "zvoner, zvoneri s.m. v. zvonac. "
];

module.exports = {
  dictionary: data
};