const data = [
  "a fi dus cu funia în larg expr. 1. a-şi mărturisi rapid vina în anchetă. 2. a se intimida în faţa anchetatorilor din cauza lipsei de experienţă.     ",
  "apa, ape s.f. (expr. Vine apa!) poliţia! ",
  "anti  prefix  antinevralgic. ",
  "bulan, bulane s.n. 1. bastonul supraveghetorului din locul de deţinere şi din escortă. 2. bărbat fără experienţă în relaţiile cu femeile. 3. noroc. 4. dos, fund. 5. picior.  ",
  "grandate s.f.pl.  cărţi de joc măsluite prin diverse semne aplicate prin scriere sau împungere. ",
  "antreu, antreuri s.n. buzunar. ",
  "mortăciune, mortăciuni s.f. 1. carne de foarte proastă calitatate  pregătită în mâncare. 2. cadavru. 3. crimă. 4. v. mălai mare.  5. deţinut bolnav cronic, cu sănătatea şubredă. 6. mandat de executare a pedepsei. ",
  "a fi băgat la salată expr. a fi închis la secţia restrictivă. ",
  "a fi faţă expr. a fi nesincer şi răuvoitor. ",
  "a fi gros la pungă expr. a fi foarte bogat. ",
  "figurant, figuranţi s.m.  persoană care vrea să pară importantă, dar nu este.",
  "fieroaică expr. argotică bară de metal de dimensiuni mici, ascunsă la pat şi folosită în caz de scandal în cameră, iar uneori pentru atac asupra unor deţinuţi sau cadre. ",
  "fieroasă, fieroase s.f. conservă. ",
  "fiertură, fierturi s.f.  act sexual. ",
  "fomist, fomişti s.m. 1. nesătul. 2. vagabond care îşi caută hrana prin lăzile şi tomberoanele de gunoaie. ",
  "forţos, forţoşi adj. puternic.",
  "foşnitoare, foşnitori s.f. bancnotă nou-nouţă, proaspăt pusă în circulaţie. ",
  "fraier, fraieri s.m. 1. membru al completului de judecată. 2. persoană care nu ştie să se descurce, să profite într-o anumită împrejurare. 3. victima unui hoţ sau escroc. 4. poliţist. ",
  "fraier cu cioc expr. persoană de o prostie rară, prost de-a binelea. ",
  "fraieri,  fraieresc vb. v. a face pontul.",
  "fratele meu expr. prieten bun, colaborator, complice. ",
  "târfoman, târfomani s.m. afemeiat. ",
  "târlan, târlani s.m. fraier. ",
  "târnăcop, târnăcoape s.n. nas mare. ",
  "târşală, târşeli s.f. ruşine. ",
  "târşă, târşe s.n. deţinut ruşinos.",
  "târtan, târtani s.m.  v. târlan. ",
  "târtiţă,  târtiţe s.f. fund, şezut. ",
  "T. B. C. expr. tutun, băutură, cafea. ",
  "telefon, telefoane s.n. lovitură cu palma peste ureche. ",
  "teleguţă, teleguţe s.f. pachet cu obiecte coborât cu o sfoară  la geamul unei camere de deţinere de la un etaj inferior. ",
  "teleică, teleici s.f. femeie de moravuri uşoare. ",
  "trompă, trompe s.f. nas mare. ",
  "trompetist trompetişti s. m. v. taragotist. ",
  "tron, tronuri s.n. closet. ",
  "tronson, tronsoane s.n. intervalul dintre paturi în camera de deţinere. ",
  "troponei s.invar. încălţăminte. ",
  "troscău  s.invar v. trascău.",
  "trosneală  s.f.invar. v. trascău. ",
  "Vasilică  s.propr. v. vardist.  ",
  "vast, vasturi s.n. mâna. ",
  "vastangiu, vastangii s.m. hoţ de buzunare. ",
  "vămui, vămuiesc vb. a fura doar o parte din bani sau bunuri. ",
  "a vărsa guşa  expr.1.  spovedanie la preotul puşcăriei.  2.  a-l denunţa cadrelor pe un coleg de detenţie. 3. a recunoaşte fapta comisă. ",
  "a-şi vărsa oala expr. v. a vărsa guşa(2). ",
  "vărsător, vărsători s.m. v. a vărsa guşa(2). ",
  "vărsătură, vărsături s.f. posibilă victimă care are puţini bani la ea. ",
  "văruială, văruieli s.f. beţie. ",
  "văruit, văruiţi adj. beat. ",
  "zurliu, zurlii adj.pl. bolnav psihic. ",
  "zuză adj. v. zurliu.",
  "zvonac, zvonaci s.m. purtător de zvonuri, de informaţii false în puşcărie. ",
  "zvoner, zvoneri s.m. v. zvonac. "
];

module.exports = {
  dictionary: data
};